# Generated by Django 6.0.6 on 2026-07-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_socialmedialink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
