# Generated by Django 6.0.6 on 2026-08-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_post_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',)},
        ),
    ]
